### ISSUE TITLE
My Kanban rollup needs to be wider, or needs a scroll bar

### ISSUE THREAD

**Issue by busywait** [ALM-Rangers/Roll-Up-Board-Widget-Extension#11]
Roll-Up-Board would be very useful for me, but unfortunately there are too many columns on our team board to be displayed.

Other widgets (for example the Markdown widget) allow up to 10x10, but the Rollup widget only allows maximum width of 4.

Could a scroll bar or other work around for wide boards be implemented?

![image](https://cloud.githubusercontent.com/assets/3671165/25649161/f796a93a-2fca-11e7-94e7-b626c9f777a2.png)

**Comment by wpschaub** [comment]
We have no plans to implement scrolling features, but are investigating options to increase the foot print on the dashboard and for the widget to enter full-screen mode. However, core intent is to show an aggregated visual on the dashboard and complex boards, like the one above, are outliers.

**Comment by wpschaub** [comment]
Latest release 2.0.24 supports increased with. See https://blogs.msdn.microsoft.com/visualstudioalmrangers/2017/12/03/roll-up-board-widget-goes-wide for details.
