### ISSUE TITLE
Unsuccessful in configuring the widget

### ISSUE THREAD

**Issue by huntantr** [ALM-Rangers/Roll-Up-Board-Widget-Extension#18]
I just tried to use the latest version of the widget with TFS2017.2 onprem. After I select the backlog and click save, it just spins for a few minutes then eventually times out. No data is displayed.
This may be due to our team project making use of the Team Field.

**Comment by wpschaub** [comment]
Can you check if you see warnings or errors in the F12 Debugger Tools Console? If not can you capture a fiddler trace for us? The current extension is based on area path, but we’d like to understand the “spinning” behavior.

**Comment by wpschaub** [comment]
@huntantr are you seeing any warnings or errors?

**Comment by jeffrey-opdam** [comment]
Closing, due to old issue
