### ISSUE TITLE
VS402647: Widget took too long to load

### ISSUE THREAD

**Issue by gcalabro-io** [ALM-Rangers/Roll-Up-Board-Widget-Extension#19]
I have recently started getting this error.
I assume our backlog has gotten too large?
Can this be fixed?

**Comment by wpschaub** [comment]
Can you check your F12 Debugger Tools console windows for warnings and/or errors? How large is your backlog in terms of the board WIs your aggregating?

**Comment by gcalabro-io** [comment]
No errors / warnings in the console. There are 300 items in the backlog

**Comment by wpschaub** [comment]
@mikaelkrief have you seen this error before? 300 WIs should not be an issue.

**Comment by wpschaub** [comment]
@gmcalab30 are you still experiencing your issue?

**Comment by gcalabro-io** [comment]
@wpschaub It is now working, did something change?

**Comment by wpschaub** [comment]
We identified a service issue that caused this and other extensions to have the issue you described. A hotfix was deployed and as you confirmed the widget is working again for you, we can close this issue.

**Comment by gcalabro-io** [comment]
Thank you!
