### ISSUE TITLE
Exceptions returned when hitting a board that does not exist

### ISSUE THREAD

**Issue by taylorcyoung** [ALM-Rangers/Roll-Up-Board-Widget-Extension#20]
Hey ALM-Rangers,

This is Taylor Young from the VSTS Agile area dev team. We are seeing spikes in BoardDoesNotExistException from this tool. Once a user configures this widget, there is no check to see if the board still exists or has been renamed or hidden. Right now we will return this exception every time a user loads their dashboard with a bad configuration.

Would there be interest in adding a "Does board exist" check before issuing this request? 

Thanks,
Taylor Young

**Comment by wpschaub** [comment]
Fixed in 2.0.2.
