### ISSUE TITLE
Stopped working for IE (11)

### ISSUE THREAD

**Issue by ricardocovo** [ALM-Rangers/Roll-Up-Board-Widget-Extension#24]
Hello Guys, thanks you very much for this extension. it works great.

The widget stopped working on IE11, we first noticed it yesterday (Oct. 3, 2017). It still works well in Chrome, though it takes longer to load.

Here is what we see on the screen:
![rollupwidgetissue](https://user-images.githubusercontent.com/1675545/31175849-b09e886c-a8de-11e7-85bc-66d2451b1b00.PNG)

We get this no errors, but this warning seems related:
![rollupwidgetissue_console](https://user-images.githubusercontent.com/1675545/31175923-f7301ffc-a8de-11e7-85af-5e06f06a1068.PNG)

Hope this helps finding the issue, let me know if this is something that would be fixed.

Thanks,
-Ricardo

**Comment by wpschaub** [comment]
Ricardo, are you running the extension on VSTS or TFS in-prem? 

Until a Promise Polyfill hotfix is added to the web platform of TFS on-prem this and other extensions updates are not supported with Internet Explorer (IE) 11.0.

**Comment by ricardocovo** [comment]
We are running on VSTS.

**Comment by wpschaub** [comment]
Can you capture a Fiddler trace for us to investigate your issue? Best would be to create a test dashboard with just the roll-up board widget to focus the trace.

**Comment by ricardocovo** [comment]
I am including two traces:

- one for the dashboard (includes the widget twice), and 
- one for the configuration section, which is also broken (see below), I do not get an option of Backlogs.
![image](https://user-images.githubusercontent.com/1675545/31178348-c44c5710-a8e6-11e7-9129-8af3d74d08ed.png)
[Traces.zip](https://github.com/ALM-Rangers/Roll-Up-Board-Widget-Extension/files/1355952/Traces.zip)

**Comment by wpschaub** [comment]
Thank you. We'll investigate.

**Comment by ricardocovo** [comment]
Hi, wondering if you found the issue... 
Thanks!

**Comment by Rumpfinger** [comment]
I have the same problem
The issue is still open with the newest version. It doesn't run with IE11 on TFS 2017.

**Comment by Rumpfinger** [comment]
Any news? Will it ever be fixed?

**Comment by pabrams** [comment]
We also use Microsoft Internet Explorer 11 and are having the same issues.  The first error my browser gives me is "Error: Object doesn't support property or method 'includes'".  Almost every extension that comes from anyone affiliated with Microsoft has similar problems:  the Microsoft browser is not supported by the Microsoft extension. (Non-Microsoft browsers work fine.  Microsoft Edge might also work, but I don't use that one.) The problem can be fixed easily by adding a polyfill.  
I'll submit a PR if my organization ever puts through the paperwork to allow me to contribute to open source.

**Comment by jeffrey-opdam** [comment]
We have discussed internally. We currently do not support IE.
