### ISSUE TITLE
Empty Feature Swim Lanes

### ISSUE THREAD

**Issue by cycling-jim** [ALM-Rangers/Roll-Up-Board-Widget-Extension#38]
![image](https://user-images.githubusercontent.com/36725920/36526179-78c49a4c-17ad-11e8-9b62-1f3fce72392c.png)

Console shows the following
![image](https://user-images.githubusercontent.com/36725920/36526364-40520dce-17ae-11e8-97db-11e716e775ff.png)

The Microsoft plugin for deliver plans was recently enabled (https://docs.microsoft.com/en-us/vsts/work/scale/review-team-plans).  Not sure if related.

Microsoft Visual Studio Team Foundation Server Version 16.122.27102.1

**Comment by wpschaub** [comment]
@cycling-jim can you share a snip of your feature dashboard swimlane configuration, so that we can investigate the "no name" swim lane.

What data are you expecting to see in each lane and what are the WIQL queries (as above) returning when run manually?

**Comment by jeffrey-opdam** [comment]
outstanding for more then a year, closing
