### ISSUE TITLE
Widget wont work with many simlines

### ISSUE THREAD

**Issue by ndeeH** [ALM-Rangers/Roll-Up-Board-Widget-Extension#4]
see:
![Pic](https://cdn.pbrd.co/images/kGYMNnWUh.png)

Would be great, if a scrollbar would arise.

Or sort the swimlanes from topmost to "other".
And do not display empty lines.

Thank you, Andi

**Comment by wpschaub** [comment]
Andi, the goal of this extension is to display the same structure of the Kanban board. We are intentionally not sorting data or supressing empty lanes.

It's very unusual to see a board with this many swimlanes and we'll have to investigate the feasibility of adding a scrollbar.  

@mikaelkrief thoughts?

**Comment by wpschaub** [comment]
@mikaelkrief  we can add 10 row support to support the swimlane scenario as well.

**Comment by wpschaub** [comment]
@weird-dreams how many cells do you need? I'm hesitant to add a lot of row options, because the user already has to scroll through many variations when configuring the widget.

**Comment by ndeeH** [comment]
@wpschaub We are looking for a better view that we get through TFS charts.
![image](https://user-images.githubusercontent.com/11518242/33633881-9270ddb2-da12-11e7-840b-2743c7642211.png)
The TFS charts are sorted by value descending and have a final node "(others)" that collects the "rest".
To get an overview for a big kanban board this is ok - but not as detailed as in your extension.

So when you do want roll-up board to be smart and slim for these extrem cases:

- do not add swimlanes without any items (most people are not interested in empty 0 lines)
- sum up in an "(others)" lane before a scroll bar would arise

TIA, Andi

**Comment by wpschaub** [comment]
OK, we just pushed a PR that adds support for 1-10 rows x 3-10 columns. Once released you should be able to get a better (not cut off) view of the board.

**Comment by wpschaub** [comment]
v2.0.26 delivered support for 1-10 rows x 3-10 columns.
