### ISSUE TITLE
Widget cannot load data

### ISSUE THREAD

**Issue by thoaingan** [ALM-Rangers/Roll-Up-Board-Widget-Extension#41]
I can configure the widget but it doesn't display any data. Below are the errors I see from the Debugger window. Any help is greatly appreciated!

Uncaught DOMException: Failed to read the 'sessionStorage' property from 'Window': The document is sandboxed and lacks the 'allow-same-origin' flag.
    at Object.na.getAndResetPendingTask (<anonymous>:69:28801)
    at a.addPendingTask (<anonymous>:65:8226)
    at D (<anonymous>:64:17877)
    at c (<anonymous>:64:18398)
    at d (<anonymous>:63:8456)
    at h.promiseDispatch.j (<anonymous>:63:8721)
    at q.d.promiseDispatch (<anonymous>:63:2730)
    at <anonymous>:63:1493
    at MessagePort.c (<anonymous>:63:6156)
/_apis/public/gallery/publisher/ms-devlabs/extension/RollUpBoard/2.0.33/assetbyname/dist/WidgetRollUpBoard.js:1 RollUp board Widget: your VSTS User ID : 0c8828b7-c531-46d5-9e04-de93692cc5dc
/_apis/public/gallery/publisher/ms-devlabs/extension/RollUpBoard/2.0.33/assetbyname/dist/WidgetRollUpBoard.js:1 RollUp board Widget: your VSTS Account ID : bd11c8dc-7993-4be2-a273-e928c6d32fc1
/_apis/public/gallery/publisher/ms-devlabs/extension/RollUpBoard/2.0.33/assetbyname/dist/WidgetRollUpBoard.js:1 Context : TFS On-Premise
/_apis/public/gallery/publisher/ms-devlabs/extension/RollUpBoard/2.0.33/assetbyname/dist/WidgetRollUpBoard.js:1 Creating new TelemetryClient!
/_apis/public/gallery/publisher/ms-devlabs/extension/RollUpBoard/2.0.33/assetbyname/dist/WidgetRollUpBoard.js:1 TelemetryClient settings key: XDISABLE************
/_apis/public/gallery/publisher/ms-devlabs/extension/RollUpBoard/2.0.33/assetbyname/dist/WidgetRollUpBoard.js:1 TelemetryClient settings extension context: RollUpBoardWidget
/_apis/public/gallery/publisher/ms-devlabs/extension/RollUpBoard/2.0.33/assetbyname/dist/WidgetRollUpBoard.js:1 TelemetryClient settings disableTelemetry: true
/_apis/public/gallery/publisher/ms-devlabs/extension/RollUpBoard/2.0.33/assetbyname/dist/WidgetRollUpBoard.js:1 TelemetryClient settings disableAjaxTracking: true
/_apis/public/gallery/publisher/ms-devlabs/extension/RollUpBoard/2.0.33/assetbyname/dist/WidgetRollUpBoard.js:1 TelemetryClient settings enableDebug: false
7/BSGCollection/BSG/App%20Dev%20Prod.%20Support/_apis/wit/wiql Failed to load resource: the server responded with a status of 400 (Bad Request)
7Content?bundle=vss-bundle-ext-core-vmRBvZ4VpkIyISgvnm0ZKfOsvMHEgML6x8fgxF73yR50=:35 TypeError: Cannot read property 'EnableAppInsightTelemetry' of undefined
    at WidgetRollUpBoard.js:1
    at l (Content?bundle=vss-bundle-ext-core-vmRBvZ4VpkIyISgvnm0ZKfOsvMHEgML6x8fgxF73yR50=:27)
    at Content?bundle=vss-bundle-ext-core-vmRBvZ4VpkIyISgvnm0ZKfOsvMHEgML6x8fgxF73yR50=:27
    at t.when (Content?bundle=vss-bundle-ext-core-vmRBvZ4VpkIyISgvnm0ZKfOsvMHEgML6x8fgxF73yR50=:27)
    at t.u.promiseDispatch (Content?bundle=vss-bundle-ext-core-vmRBvZ4VpkIyISgvnm0ZKfOsvMHEgML6x8fgxF73yR50=:27)
    at Content?bundle=vss-bundle-ext-core-vmRBvZ4VpkIyISgvnm0ZKfOsvMHEgML6x8fgxF73yR50=:27
    at MessagePort.t (Content?bundle=vss-bundle-ext-core-vmRBvZ4VpkIyISgvnm0ZKfOsvMHEgML6x8fgxF73yR50=:27)

**Comment by shayki5** [comment]
Also in our TFS 2017.3 the widget does not show any data (after configure).
**This errors on the console:**
TypeError: Cannot read property 'EnableAppInsightTelemetry' of undefined
POST http://tfs:8080/tfs/Collection/TP/TP%20Team/_apis/wit/wiql 400 (Bad Request)
TypeError: Cannot read property 'templateName' of undefined
ccess to Script at 'http://tfs:8080/tfs/_apis/public/gallery/publisher/ms-devlabs/extension/RollUpBoard/2.0.35/assetbyname/lib/ldclient.min.js' from origin 'null' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'null' is therefore not allowed access.

**Comment by jeffrey-opdam** [comment]
Issue has been open for almost a year, closing.
