### ISSUE TITLE
Doesn't work with latest visualstudio.com instance

### ISSUE THREAD

**Issue by shikarishambu** [ALM-Rangers/Roll-Up-Board-Widget-Extension#45]
The rollup board is not working with the latest version of visualstudio.com

**Comment by mikaelkrief** [comment]
Hi @shikarishambu can you provide more details (logs, screenshot, .... ) about your problem.
Thanks

**Comment by GaTechThomas** [comment]
Same here. The widget just says "Configure widget". When I click the gear it pops up the Configuration side panel with a spinning circle indicating loading. However, the configuration info never loads.

**Comment by JamesInDenver** [comment]
Also seeing eternal spinning on configure.  Console log is attached.

[1556917032225.log](https://github.com/ALM-Rangers/Roll-Up-Board-Widget-Extension/files/3143548/1556917032225.log)

**Comment by mikaelkrief** [comment]
Can you provide a screen shoot of your browser (like chrome) developer tools, with the error.

**Comment by JamesInDenver** [comment]
Here is a dev tools screen shot on adding the Roll-Up Board widget and clicking configure:

![ErrorScreenShot](https://user-images.githubusercontent.com/7646941/57458169-1b160200-722e-11e9-8da0-11420d8b7596.png)

**Comment by mikaelkrief** [comment]
Thanks, I get the same error and behavior. I will investigate

**Comment by jeffrey-opdam** [comment]
Issue is fixed
