### ISSUE TITLE
Roll-up Board is not working properly in New Navigation Azure DevOps

### ISSUE THREAD

**Issue by Umer2278** [ALM-Rangers/Roll-Up-Board-Widget-Extension#47]
My Roll-up Board is picking user story data from another team (By default project Team)  instead of my Team.
When you click on the Roll-Up Board it takes you to the By default project Team (Platts Team) story board.

![image](https://user-images.githubusercontent.com/47641250/52807789-5204cd80-30ae-11e9-94c5-0babba3f2f95.png)

![image](https://user-images.githubusercontent.com/47641250/52807896-837d9900-30ae-11e9-9b5e-a83d5c254af9.png)

**Comment by ChrisGibson1982** [comment]
I've noticed this issue for Features and Epics as well.  However it can be intermittent.  For example if you add Roll up boards for Epics, Features and PBLI on Team B's Dashboard, it will show stats for Team A.  However if you then go to Team B's Work Item board and then switch back to Team B's Dashboard, it sometimes shows the correct stats.  Sorry it this sounds confusing its a strange one

**Comment by Ivers07** [comment]
Same issue here. 

If you create a dashboard for a team that is not the default team it will still show the stats for the default team (even if it's showing the create team/dashboard at the top). The only way I can find to get it display the stats for the correct team is to reselect the dashboard at the top of the page.

I've encountered a similar issue on other extensions e.g [Product Vision](https://marketplace.visualstudio.com/items?itemName=agile-extensions.product-vision&targetId=263fd78d-5f8d-4f48-94ea-6dc2293c6ab0&utm_source=vstsproduct&utm_medium=ExtHubManageList)

**Comment by Umer2278** [comment]
Hi ALM-Rangers,
Can we get update on those issues as they are creating too much mess as
management just pull out reports from widgets so please take this as
priority

Thanks
Umer

**Comment by jeffrey-opdam** [comment]
We will investigate

**Comment by mikaelkrief** [comment]
This issue is fixed
