### ISSUE TITLE
Enhancement: Make The Plugin Iteration/Team agnostic

### ISSUE THREAD

**Issue by HeroMaxPower** [ALM-Rangers/Roll-Up-Board-Widget-Extension#5]
Hi Microsoft great plugin would it be possible to make this filterable for Iteration and Team agnostic.

Would be nice to see how a team is closing off epics feature and PBI's

Regards Max

**Comment by wpschaub** [comment]
Hi Max - we've got features on our backlog for filtering on a specific path, team project, or team on our backlog, but no immediate plans to implement them. 

The scenario of iteration filtering feels out-of-scope within the context (present aggregated view of Kanban Board) of this extension. 

Does the [Delivery Plans](https://marketplace.visualstudio.com/items?itemName=ms.vss-plans) extension not deliver the view you're after?

**Comment by wpschaub** [comment]
No response for 6+ months.
