### ISSUE TITLE
widget is not working

### ISSUE THREAD

**Issue by jimbothh** [ALM-Rangers/Roll-Up-Board-Widget-Extension#50]
I can't seem to configure or add a new roll-up board onto the dashboard since last week.  I tried uninstall and reinstall the widget but the issue still persists.  
![image](https://user-images.githubusercontent.com/50336296/57242403-626b7b00-7001-11e9-8f29-6af902325881.png)

![image](https://user-images.githubusercontent.com/50336296/57242417-70b99700-7001-11e9-835e-4f5bf0529cd8.png)

**Comment by towerbe** [comment]
We're seeing very similar behavior.  Existing Roll ups work, but cannot create any new ones.  Configure page just sits and spins for days.

**Comment by bensnapper** [comment]
> We're seeing very similar behavior. Existing Roll ups work, but cannot create any new ones. Configure page just sits and spins for days.

I've just installed Rollups and i can't create anything. the Config page just sits and spins

**Comment by mikaelkrief** [comment]
This issue was fixed in the last release
